---
name: ci
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  PUPPET_FORGE_TOKEN: ${{ secrets.PUPPET_FORGE_TOKEN }}
  BUNDLE_RUBYGEMS___PUPPETCORE__PUPPET__COM: forge-key:${{ secrets.PUPPET_FORGE_TOKEN }}
jobs:
  Spec:
    if: ${{ github.repository_owner == 'puppetlabs' }}
    uses: puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main
    secrets: inherit
  Acceptance:
    if: ${{ github.repository_owner == 'puppetlabs' }}
    needs: Spec
    uses: puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main
    with:
      flags: --provision-service
    secrets: inherit
