---
name: mend
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  mend:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: puppetlabs/cat-github-actions/.github/workflows/tooling_mend_ruby.yml@main
    secrets: inherit
    with:
      product_name: Puppet Enterprise
